# Generated by Django 4.2.16 on 2024-11-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_savingproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtfProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmsNm', models.TextField()),
                ('fltRt', models.FloatField()),
                ('trqu', models.IntegerField()),
                ('bssIdxIdxNm', models.TextField()),
            ],
        ),
    ]
