# Generated by Django 4.2.16 on 2024-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('participant_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('test_img', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_count', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
