# Generated by Django 4.2.16 on 2024-11-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='attribute_key',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='attribute_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
