# Generated by Django 4.2.16 on 2024-11-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_savingproducts'),
        ('tests', '0002_alter_testresult_attribute_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='deposit_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.depositproducts'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='saving_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.savingproducts'),
        ),
    ]
