# Generated by Django 4.2.16 on 2024-11-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_etfproducts'),
        ('tests', '0003_testresult_deposit_product_testresult_saving_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='etf_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.etfproducts'),
        ),
    ]
