# Generated by Django 4.2.16 on 2024-11-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testresult_etf_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='attribute_value',
            field=models.TextField(),
        ),
    ]
